name: 'dbt_meteostat'
version: '1.0.0'
config-version: 2

profile: 'default' 

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_meteostat:


  models:
  my_new_project:
    # Applies to all files under models/example/
    staging:
        materialized: table
      # Applies to all files under models/prep/
    prep:
        materialized: table
    # Applies to all files under models/mart/
    mart:
        materialized: table